### ISSUE TITLE
Fail to build with Maven 3.2.1

### ISSUE THREAD

**Issue by metalik** [cpputest/CppUTestEclipsePlugin#10]
> $ mvn --version
> Apache Maven 3.2.1 (ea8b2b07643dbb1b84b6d16e1f08391b666bc1e9; 2014-02-15T01:37:52+08:00)
> Maven home: /usr/local/Cellar/maven/3.2.1/libexec
> Java version: 1.6.0_65, vendor: Apple Inc.
> Java home: /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
> Default locale: en_US, platform encoding: MacRoman
> OS name: "mac os x", version: "10.9.5", arch: "x86_64", family: "mac"

Got the following exception when build with maven3

> Exception in thread "main" java.lang.NoSuchMethodError: org.apache.maven.execution.MavenSession.getRepositorySession()Lorg/sonatype/aether/RepositorySystemSession;
>     at org.eclipse.tycho.core.maven.utils.PluginRealmHelper.execute(PluginRealmHelper.java:86)
>     at org.eclipse.tycho.p2.resolver.P2TargetPlatformResolver.getDependencyMetadata(P2TargetPlatformResolver.java:159)
>     at org.eclipse.tycho.p2.resolver.P2TargetPlatformResolver.setupProjects(P2TargetPlatformResolver.java:141)
>     at org.eclipse.tycho.core.resolver.DefaultTychoDependencyResolver.setupProject(DefaultTychoDependencyResolver.java:76)
>     at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead(TychoMavenLifecycleParticipant.java:59)
>     at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:317)
>     at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
>     at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
>     at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
>     at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
>     at java.lang.reflect.Method.invoke(Method.java:597)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

**Comment by FlYnN91** [comment]
I have the same issue. Could anyone advise?

**Comment by terryyin** [comment]
Hi, this project unfortunately didn't continue for very long time. Sorry.
